### ISSUE TITLE
can't run tests

### ISSUE THREAD

**Issue by MattBlack85** [astrobin/astrobin#1768]
Hi!

I started to look into the code and wanted to propose some changes but I can't run the tests, is this running on python 2? Is there any way to run CI tests?

**Comment by siovene** [comment]
Hi Matt,

yes, it's running on Python 2.7.

Did you go thru README.md? It mentions testing specifically.

Please let me know if you have specific error messages or something.

**Comment by MattBlack85** [comment]
@siovene I think it was late and my Brian wasn't working well, I field to run compose, maybe I have to run docker-compose?
would you be interested in hooking up github actions that would run tests against PRs? I could work on that

**Comment by siovene** [comment]
Hi @MattBlack85, my CI/CD runs on AWS CodeBuild / CodePipelines. I had it on Trevis CI but due to memory requirements, I couldn't run the whole integration test stack. If you're familiar with AWS I can see if I can add your account so you can view the output of the build, but otherwise, I don't think I need GitHub action as I'm pretty well covered in terms of CI and CD :D

**Comment by MattBlack85** [comment]
@siovene ah ok makes sense now! I work with AWS every day so yeah, I feel quite familiar with It, I did see the codebuild in other PRs but I didn't know what was running!

**Comment by siovene** [comment]
@MattBlack85 ok cool, please send me an email address using support@astrobin.com and I will add an IAM user with permissions to see the CodeBuild jobs!
