### ISSUE TITLE
Make forum pagination numbered, as opposed to prev/next as it is now

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#549]
The forums are getting more popular, and some threads are LONG. Add paged navigation.

**Comment by skaven81** [comment]
From @siovene 

To add numbered pagination to the forum, you can probably get away with only editing templates/pybbm/pagination.html

Note that pyybm has it’s own pagination file, whereas the other AstroBin “native” pages use templates/pagination.html

I would like that there be templates/pagination_simple.html (just prev/next) and templates/pagination_full.html (numbered pages), so that they can be reused.

Ok these’s also a third pagination on AstroBin: endless pagination (https://django-el-pagination.readthedocs.io/en/latest/) that is used for infinite scrolling.

You can see the variables available to regular pagination here: https://docs.djangoproject.com/en/1.9/topics/pagination/
(there’s also a nice example)

**Comment by skaven81** [comment]
@siovene you can assign this one to me.

**Comment by siovene** [comment]
@skaven81 I just noticed that the "View all" notifications page has numbered pagination, so you could see if you can generalize all of those into a centralized place, that would be great!

**Comment by siovene** [comment]
#497 is related.

**Comment by skaven81** [comment]
I think I've got a handle on how to approach this.  I'm going to create three pagination templates:
* `astrobin/templates/pagination_simple.html` - simple prev/next pagination
* `astrobin/templates/pagination_paged.html` - pagination with page numbers (with sanity -- it will only show the nearest ~3-5 pages or so, with "first" and "last" page links as well).
* `astrobin/templates/pagination_endless.html` - endless scrolling mod

I'll then update all the templates that reference one of the existing pagination templates and replace them with the most appropriate generic template.

I've already confirmed that the template search path picks up stuff in the `astrobin/templates` directory before `astrobin/templates/pybb`, and that (surprisingly) there doesn't seem to be an issue with namespace within the pybb templates.

**Comment by siovene** [comment]
> astrobin/templates/pagination_paged.html
Sounds good! Maybe make that `pagination_numbered`? All paginations are paged, by definition :)

**Comment by skaven81** [comment]
I think the "endless" paging can stay how it is now -- the code is already tucked neatly under `el_pagination` and I think trying to abstract it out will just make it more confusing.

**Comment by skaven81** [comment]
Also, I couldn't find anywhere that `templates/activities.html` was being used; it seems to have been replaced by `templates/index/stream_page.html`, right?

**Comment by siovene** [comment]
Yes that's right.
