### ISSUE TITLE
Connect with the SIMBAD database

### ISSUE THREAD

**Issue by siovene** [astrobin/astrobin#595]
- [ ] Investigate if they offer an actual API
- [ ] Add an app to connect to it and provide querying capabilities
- [ ] Ideally, integrate the data within AstroBin, so the user doesn't need to leave the site for the basic information, but link back to SIMBAD for the full data

http://simbad.u-strasbg.fr/simbad/

**Comment by siovene** [comment]
@skaven81 the first parts of this are purely backend, do you think you would find this interesting?

**Comment by siovene** [comment]
Looks like you can query via URL and get data as JSON, e.g.: 

http://simbad.u-strasbg.fr/simbad/sim-nameresolver?Ident=M31&data=J,M(U,B,V),S,I&output=json

**Comment by siovene** [comment]
Documentation here:

http://simbad.u-strasbg.fr/simbad/sim-nameresolver

**Comment by siovene** [comment]
Object classification in Simbad:

http://simbad.u-strasbg.fr/simbad/sim-display?data=otypes

**Comment by skaven81** [comment]
Yeah I can work on this.  Note that it may take a few weeks since I can really only work on it a few hours a week.  But if that's OK then yeah I can take this on.

When you say "Add an app", I presume you mean add a new `astrobin_app_simbad` directory that contains a Django "app" or "plugin"?  Looking at the other "apps" it looks like they're kind of self-contained Django things, with their own individual admin, urls, views, templates, etc.  Then the main astrobin Django site imports the app?

For the Simbad bits, you've already found the API documentation; so what would the app be abstracting?  Just creating a Python class that can query Simbad, and a set of Astrobin API URLs that interface to that class?  What functions/behaviors would you like implemented?

**Comment by siovene** [comment]
> Note that it may take a few weeks since I can really only work on it a few hours a week. But if that's OK then yeah I can take this on.

Of course, just do what you want when you want! I appreciate any kind of contribution at all :-)

> When you say "Add an app", I presume you mean add a new astrobin_app_simbad directory that contains a Django "app" or "plugin"?

Yes, you can create one with `django-admin startapp`: https://docs.djangoproject.com/en/1.9/ref/django-admin/#startapp

> Looking at the other "apps" it looks like they're kind of self-contained Django things

Yes, relevant documentation here: https://docs.djangoproject.com/en/1.9/intro/reusable-apps/

> Then the main astrobin Django site imports the app?

Yes, see `INSTALLED_APPS` in `astrobin/settings/components/basic.py`.

I think the best app to take inspiration from is the `astrobin_apps_platesolving` one.

> For the Simbad bits, you've already found the API documentation; so what would the app be abstracting? Just creating a Python class that can query Simbad, and a set of Astrobin API URLs that interface to that class? What functions/behaviors would you like implemented?

Hmm ok let me put on my thinking cap. This also depends on what UI we want provided. Let's start with some requirements. The object is that AstroBin contain a bit more scientific data. I would want to:

- [ ] Display some data directly in the image page (data is cached with async retrieval once a month or something)
- [ ] Link to the source Simbad page (because it doesn't make sense to include everything)
- [ ] Each subject has it's own page, again with Simbad data, link to Simbad, example images from AstroBin, etc
- [ ] You can "follow" a subject and get notifications when new images of it are posted

So this will require the Simbad app to have a connector part, much like the platesolving app connects to Astrometry.net, and an API to expose the things it collects.

Now that I think about it, this should actually be an `astrobin_apps_subjects` with a Simbad backend foro data retrieval, but there could be more.

Maybe this is a bit too big a task for you at this time, perhaps stick to a bit easier tasks until you feel like you know the codebase enough to have a look at this?

**Comment by skaven81** [comment]
> data is cached with async retrieval once a month or something

Where would you want to cache this?  In Elasticsearch or PostgreSQL?

To be clear, your objective is to _mirror_ the SIMBAD database periodically, and have Astrobin query the local mirror rather than reach out directly to SIMBAD?

Assuming the mirroring process isn't overly onerous or time consuming, then I agree that this is a good way to do things.  FWIW I recommend using Elasticsearch for this, rather than SQL.  I think we'll have better luck with constructing meaningful searches (especially using coordinate search) in Elasticsearch.

> Each subject has its own page

"Subject" in this context means "user-uploaded image"?  Or "entry in the SIMBAD database"?

The former suggests that the SIMBAD app will really just be a data provider used for adding extra information to a plate-solved image.  The latter suggests creating a whole "SIMBAD browser" where a user can click a link on an image and be taken to a bespoke page where they can examine the SIMBAD data.

> Maybe this is a bit too big a task for you at this time

No, I have a handle on this.  I'm asking lots of questions not because I'm not sure where to start, but because I want to make sure I understand your vision of what the end result will look like. No sense in writing a bunch of code that just has to be ripped out because it wasn't what you wanted.

Let's see if I'm getting close.

You would like to use SIMBAD as the "canonical data source" for scientific information about "subjects".

A "subject" is a DSO that Astrobin users may take photos of.  There may be a photo of "M42" or "the Orion Nebula" or "NGC 1976" or "the Trapezium" or "Orion's Belt" or "Photo from this weekend".  All of these photos should, via plate-solving data, end up referencing the same "subject".  So an Astrobin user can look at a photo of M42 and be able to get a list of other, similar photos of the same subject.

We get some important information from plate-solving data.  We know the RA/Dec coordinates of each corner of the image.  We know some reasonably official name / identifier for subjects in the image (I'm assuming this because you can hover over the image and see NGC and M numbers attached to the circles).  That _should_ be sufficient data to make a confident link to a set of SIMBAD subjects for each image.

Importantly, the link is from uploaded image -> plate solving data -> list of SIMBAD subjects.

Once an image is "tagged" with a list of SIMBAD subjects, users should be able to examine this list, which might show a short "preview" of important scientific data right on the image detail page (along with the capture info, for example).  The user should be able to click on one of the subject names to be taken directly to the SIMBAD page (in a new tab) for more detailed information.

Users should also be able to search for a specific subject.  If a user uses Astrobin search and searches for "M42", it should start by trying to find a direct match in the SIMBAD database.  If one is found, it can then find all the images with that specific subject in the image.  If no exact match is found, it can fall back on looking for images with that string in the title (using Elasticsearch) and based on those search results, present a list of matches that might be what the user was looking for.

To implement this vision, we need a number of components.

1. We need a way to periodically mirror SIMBAD into Elasticsearch (or something).
2. We need an API for querying the local mirror of SIMBAD, which should allow searching by object name / catalog number / coordinates, or a combination of those.  The search results should be SIMBAD subject IDs that can be retrieved directly from the local database.
3. We need a Django admin page for maintaining the SIMBAD database (or maybe just some scripts?) and the ability to do searches for diagnostic purposes, and to examine SIMBAD matching logs (we need to have a straightforward way to troubleshoot why a given image didn't get associated with the right SIMBAD subject, when it inevitably fails).
4. We need a Django app (??) that can render SIMBAD data "previews" that are included in an image's details page.
5. We need to update the image upload pipeline so that an extra step is added after plate-solving, to associate SIMBAD subject IDs with the image.  There also needs to be something that maintains this data (and attempts to add SIMBAD data to images that don't already have it).

This whole thing feels more like an Epic, with at least five Stories.  It might be easiest to approach this task by breaking it down into smaller Stories or Sub-Tasks that we can work on a little at a time.  That way we don't end up with a giant blob of tens of thousands of lines of code being dropped into the project all at once -- we add a little at a time until the whole feature is fully implemented.  This would also allow us to collaborate a bit more, and would act as a bit of insurance in case I am not able to devote as much time as I'd like to it.

**Comment by skaven81** [comment]
I have looked into the SIMBAD API and it looks like they don't offer the ability to mirror its contents.  Each uploaded image will be linked to a SIMBAD document, so what we probably need is two pieces:

1. An Astrobin-internal app that acts as an interface to SIMBAD.  You give it some basic data (presumably from the plate-solving results) and it returns a list of SIMBAD documents, one for each object in the image (that the plate solver recognized).  This should utilize a caching mechanism: if a particular object has been looked up before, it should preferentially retrieve it from Elasticsearch rather than go back to SIMBAD for the JSON blob.  If the object ID isn't in Elasticsearch, it should go back to SIMBAD and get fresh data.

2. A scanner that periodically goes through all the uploaded photos and keeps the Elasticsearch database up to date, by essentially uniq-ifying the entire list of plate-solved objects and querying each of them.  Those that aren't in Elasticsearch will get added.  This should ensure that Astrobin users would not be likely to be impacted by a SIMBAD API outage.

The data in Elasticsearch can be stored in daily indexes, with old indexes dropped after 14, 28 days or whatever makes sense.  Elastic.co dropped support for the `_ttl` attribute in 2.0 and suggests using time-based indices instead, as deleting an index is a lot cheaper than deleting documents: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-ttl-field.html

**Comment by skaven81** [comment]
One interesting limitation for SIMBAD is that they rate-limit every IP to 6 requests/sec.  When everything is up and running and the Elasticsearch data is warm, this shouldn't be an issue.  But when the scanner runs, especially right after old data is purged, it will be easy to exceed this limit.  There will need to be an internal rate limiter to prevent getting blacklisted.

**Comment by skaven81** [comment]
It looks like the name resolver is able to return sufficient data for display within Astrobin without needing a followup query to the object-specific API (which is only able to return data in `votable` format, which appears to be an XML-like format.

Here's an example query that I think returns everything we want in a basic object query:
```
$ curl 'http://simbad.u-strasbg.fr/simbad/sim-nameresolver?ident=NGC+3034&data=@,J,I.0,C.0(V),T(M),D,I&option=strict&output=json'
[{
  "dim_angle": 67,
  "mtype": "I0edge ",
  "dim_minaxis": 1.621999979019165,
  "ra": 148.96845833333333,
  "dec": 69.67970277777778,
  "oid": 433918,
  "dim_qual": "C",
  "dim_bibcode": "2006AJ....131.1163S",
  "mainId": "M 82",
  "dim_majaxis": 5.070000171661377,
  "idlist": [
    "1AXG J095549+6940",
    "1E 0951+69.8",
    "1ES 0951+69.9",
    "1FGL J0956.5+6938",
    "1Jy 0951+69",
    "1Jy 0951+699",
    "1RXS J095550.4+694052",
    "2E 0951.7+6955",
    "2E 2197",
    "2FGL J0955.9+6936",
    "2MASX J09555243+6940469",
    "2MFGC 7685",
    "3C 231",
    "3C 231.0",
    "3CR 231",
    "3FGL J0955.4+6940",
    "4C 69.12",
    "4U 1004+70",
    "6C 095143+695502",
    "7C 095143.50+695500.00",
    "87GB 095143.5+695452",
    "8C 0951+699",
    "APG 337",
    "[B93] 14",
    "[BAG2012] 148.9211+69.6846",
    "BWE 0951+6954",
    "[CAB95] IRAS F09517+6954",
    "[CHM2007] HDC 552 J095552.43+6940469",
    "[CHM2007] LDC 842 J095552.43+6940469",
    "CXOM82 J095549.7+694043",
    "DA 277",
    "[DML87] 745",
    "[DSL2000] 0951+700",
    "GB6 B0951+6955",
    "HIJASS J0955+69B",
    "INTREF 396",
    "IRAS 09517+6954",
    "IRAS F09517+6954",
    "JVAS J0955+6940",
    "KPG 218b",
    "LEDA 28655",
    "M 82",
    "[M98c] 095145.3+695511",
    "MCG+12-10-011",
    "NAME Cigar Galaxy",
    "NAME UMa A",
    "NGC 3034",
    "[NKB95] N3034",
    "NRAO 341",
    "NVSS J095551+694046",
    "PBC J0955.7+6941",
    "PLCKERC -100 G141.42+40.57",
    "PRC D-13",
    "PSCz Q09517+6954",
    "QSO B0951+699",
    "[R97] NGC 3031 1",
    "RAFGL 1388",
    "RBS 809",
    "RGB J0955+696",
    "RGB J0955.9+6940",
    "[RPS97] NGC 3034 2",
    "RX J095550+69406",
    "RX J0955.8+6940",
    "S4 0951+69",
    "S4 0951+699",
    "SDSS J095551.73+694048.6",
    "[SPS97] 8",
    "SWIFT J0956.1+6942",
    "TeV J0955+696",
    "[TSA98] J095541.25+693927.31",
    "UGC 5322",
    "UT 0951+699",
    "UZC J095557.0+694110",
    "[VDD93] 100",
    "VLSS J0955.8+6940",
    "WB 0951+6954",
    "WMAP J0955+6940",
    "WN B0951.7+6954",
    "WN B0951.7+6954A",
    "[WZX98] 09517+6954",
    "Z 0951.7+6955",
    "Z 333-8",
    "[ZEH2003] RX J0955.8+6940 1"
  ],
  "otype": "Interacting Galaxies",
  "dim_wavelg": "I"
}]
```

* `ident=NGC+3034` - ident query (as opposed to a bibcode or coord+radius query)
* `option=strict` - don't try to use a regex to find the object -- use strict matching.  We probably want this enabled if we're going to use data from the plate-solver to lookup objects.
* `output=json` - obvious
* `data=@,J,I.0,C.0(V),T(M),D,I`
** `@` - `oid` attribute -- the (presumably) unique identifier for the object.  It looks like this might only be used internally within SIMBAD (you can't query using this ID) but it is probably handy for us to keep it around to be able to unambiguously identify two documents referring to the same object.
** `J` - `ra` and `dec` attributes, in decimal.  There are some formatters available that can return this in sexagesimal, but then we'd have to parse the strings.  Easier to just do the decimal to sexigesimal conversion within our app.
** `I.0` - `mainId` attribute.  The "main" name for the object
** `I` - `idlist` attribute.  Other names for the object
** `C.0(V)` - `otype`  (object type) attribute, formatted as a "verbose" string
** `T(M)` - `mtype` (morphological type) attribute.  Note, has a trailing space that will need to be stripped
** `D` - `dim_*` attributes - object dimensions

The results come back as a list of matches, so I would hope that `option=strict` helps limit the possibility of multiple matches.  I think a reasonable approach is to assume the first returned object is the right one, and if any additional objects are returned, log a warning.  If multiple objects are returned often enough, additional code can be added that tries to pick the "best" object based on the coordinates (using the coordinates provided by the plate solver).

**Comment by siovene** [comment]
Moved to private issue tracker.
